spring:

  application:
    name: sidecarpizza

  main:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/sidecar?serverTimezone=UTC"
    username: myuser
    password: mypassword
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 30000

  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    time-zone: "UTC"
    serialization:
      indent-output: true
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
      use-big-decimal-for-floats: true
    default-property-inclusion: non_null

jwt:
  secret: sidecarsecrets

keys:
  jwt:
    primary:
      kid: jwt-1
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2NYkdle7qxRPmsuzJzGWIY4WptTBtDgsFw+gvfjxtwZc169tOyuFAtqNRcwhi7bPvWAY/n84VIu4NRaeYh3VjOT8+dkhsYRr6KmULUX5T7jUCdm0n2oIJ/yb0c9QyAfM4AvsNZsYx95ZeYJoo7yl2Bsa7Az1WS8QLRedADv/zbcO60SbR3cEUaZdE5RF3XM3cb3WJChgDgYZr7e4cTWiQ5asMmCf1BjbNs7xmQa3QtKEEgjWvbiMrLMsg/ewmwkTEdPMuGrjb6du2Ay1Prxb3nPyWjkB2pW3WDU+ck2wqCFqyLXdnc+yBTF1iqMrwnf2bCImgO/MPktFUYk0dpNvvQIDAQAB
      private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDY1iR2V7urFE+ay7MnMZYhjham1MG0OCwXD6C9+PG3BlzXr207K4UC2o1FzCGLts+9YBj+fzhUi7g1Fp5iHdWM5Pz52SGxhGvoqZQtRflPuNQJ2bSfaggn/JvRz1DIB8zgC+w1mxjH3ll5gmijvKXYGxrsDPVZLxAtF50AO//Ntw7rRJtHdwRRpl0TlEXdczdxvdYkKGAOBhmvt7hxNaJDlqwyYJ/UGNs2zvGZBrdC0oQSCNa9uIyssyyD97CbCRMR08y4auNvp27YDLU+vFvec/JaOQHalbdYNT5yTbCoIWrItd2dz7IFMXWKoyvCd/ZsIiaA78w+S0VRiTR2k2+9AgMBAAECggEBAMkkzKoi9Gnc64NS1pvS+cuivQyBbDa7rNqvmpLfbYo0ksdZamBrHHXrOwW2OKAcM1Ue4dCjPyPegEBu/PlTZ5fNi4ZRj1nW1yr6tAPTV1RGxhtlIpKGj45YXEsin3MPGVP0e2e2uiQd9K4s9Nh+1PFFI5I46xeR+tV5hCCFh+PQ6NFYcWWjnHXdF0dk4vZDpbxAHa3EDrK+/1DHxE3WaGEcEgK+NZevFaC127Ktg62Pl/y0fRi7Jj2BT8WHQR2gqx9+zE/XsVxwJvK/yK8Ho6uBBNJUPhL3oecTDQO1EwI4XjTwWDJD8SP2qVrK7HCp7NMMWGAnpWx/zwdpjBjYalkCgYEA9IEHiZR3fPrbOGEITygsHWUj+xtTM9/+hx3xKcemTFB2CUpl2kMjyCva6/J3utX6BkELbdJJdttbXT2yVeR1cH1Igalex9jW8b/3arOL4+Kvl3PpHJmyBM7IXj1yhWcchedJGO3knw3w4dj93udEEKzsB9u0JZYTVQpUgrpPjBsCgYEA4wgX0Oag5DwQedUM7S/BL3VEz8zaaLaB6r9b1KINkgiRVVICmklge0gDl6iXboMMf54NZTnKQ86Qz+CY/Ubv5u57U3yD0d0HmqJeDwOwM1Cl9YlfQ4Xf0/51z6EGxBsQdsRxXsvyGbZP22q/xf+VbvXoF+fkYp24Oys3rX03gQcCgYEAwPDhBcxGzjUWsNLBP9WvmjKpxgm2CoWD0RPrrtCBhk8oFgTDgwzgO6F/zBk2KhWYiz7gyfTbTBOlcVqyU91IX1A92zPQO1v9oh+eGnE8vsOvVJB/L7aJKAoVS2ip6mOHupLct/NiKbFSmKYnD7Lnn1EVoM3axp46+yx/q/lhtGkCgYANZyPozETBVJ5wYtiBhCk2gQjP77sRJX0j+6oTMoH0lhbmX5IRw7UzcfvsTyKpfokVW6JU0IWVXTOFYjAF+9Mb4gZb1mT91bumMGG3JzOWw/MYPMTn+pZNMJ+J42q/1w0wxcYfn5CqXe32+SVbLgyHYXMTPjhobgE7VQDTeCn3rwKBgE2Rek26ITfSGEQZq8n0GWmHXpW/+qefQGPG0Dz/0c8ExcdQJveTycv2rWfVbAy2MhJ1DuxsFCfsw6JqSeSFN/T8DJNZMk2nHWjvALFvYLigX2J2lvAIPUCJj3XUzIyUdwv8DkCdx5XnNlr26/lMtv97/KMoxD0tX8Vptn3pBUlA
    secondary:
      kid: jwt-2
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjEC8lnUAj5yjHTba+R8z464ssBpBKfdox7DELe9p3vx9R5UeT8gTUcvo0SUMvvn7cAqEbvrWSQKFFvLrE+c+IO3g2m3A2zSdOo2rN1tNvZbfG0gx/Zv+ec5Y5gOIIsmNqt5bJjchp6xxDRuegBZKc822RVQLKqNqooG/EpjDRSA/30Ku7JjD86A57epcXvZZyjfRjJtKtdSYtmLoI9D0TrikSpFEP3DsVAEc0boC8rGIDJjA3WGkfZ4GCod/IVW8Xr/bIZPWBSe1ghvlK1ZpXDzy+n7AY34KuPP+a3TkLrayyXVf0JTHmIWbk4ng1s3nYBM0Zs3hLqd7VcmvhIwcFQIDAQAB
      private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCMQLyWdQCPnKMdNtr5HzPjriywGkEp92jHsMQt72ne/H1HlR5PyBNRy+jRJQy++ftwCoRu+tZJAoUW8usT5z4g7eDabcDbNJ06jas3W029lt8bSDH9m/55zljmA4giyY2q3lsmNyGnrHENG56AFkpzzbZFVAsqo2qigb8SmMNFID/fQq7smMPzoDnt6lxe9lnKN9GMm0q11Ji2Yugj0PROuKRKkUQ/cOxUARzRugLysYgMmMDdYaR9ngYKh38hVbxev9shk9YFJ7WCG+UrVmlcPPL6fsBjfgq48/5rdOQutrLJdV/QlMeYhZuTieDWzedgEzRmzeEup3tVya+EjBwVAgMBAAECggEAGDTIF7Oj4CVppY4lJt/yxbX28oHlg0e3JtfkVAVBIYI0YRlkfOKMKw7lZMtfMsrUUZcPGlRijYFI1Rgh6HJ9r5M+vpQ4t9yR0lxHE6vHdBRI911ze1DkD8PEZhZv9YkR0U7FLohPX7AMZvXAWlz+hpQXhEmoD7jam6eHAb+p3BEcnPyhxUBv4z26c7/OLnGGXm5selxNNK6GScdDyESPqk+guQfxhZpZsnW8cjqbbTQM2oUfZRePYOs34Rp3LoLLv42uiiV57AZAlWTUYdQ+arVVlik4Sdc88hS8dcClK2r5SBEOMcAXV3sMzLdF+5LUCicQ5g7EnBzm2V8z3WgGVQKBgQDvon+2hcKTh3oM9HmpmqTiJw2JpUQ9wge88ZGw89v4LIxQEDGR75NZgaSyVlTPiY+roxQmurbOn16dH2hO6+yctkMhD1+DtnPOuDqDTOZebcWaT4yA7jfi3rfhaIxg9HQ4VdvhfIm9Js++NAiTMUadv3hjF0x2/PkDIiI6hgeJuwKBgQCV1MIX12KT1UmOyF3NLHsvE9YLI68lvFVQARNy/m21v44luaseh6K+dk2vINFHyNXy/KHHGhz2UBPNCfCgSXa+JeLSSsk+eECvxrPT1TwMrOHCX+Cm6VLEWe+85rpds27BRM9UwZRf8Ca0qXHlrMCrrFlLXdy+7yEg2wAJXH3sbwKBgQDgrgR+luV7u49k7CfSLMuhuyoHP6w/F1h4ACswtUQuaV5ZhwVjJjSKvHI2P5mfSQQq0mmHcpMKIgTs3tDHBo8/0+gW7DoK3ZuxW6yJBSYNrXCToThEfpZpoZbYwlS0Zx883sudnE3syqIHXPQZRh9Gsopmpiasfb3gATYElzwkFwKBgDBArqli8hpODDxxhtP2yU0mBD7eJR/wAUGctxjHm6l2oV7A5r0UTXMtQmNuHDgUE+MHPUqTvFQPAfF8jAPy5MzkAqJa92io7ZwuT+eeupISczpYCk92wPL/S9f4LnjSuo5/jI3tMc2b17tC/q1K71naTX+aIOdUt8SPAvoA0YT9AoGBAMF3egOZrYvkofiTKM3hy5MMQPYaDhTQ8/earyMur8jSql863tqZMtL+EnJO5vNYFffJclBK8PkUC2IZhfSP5OECWamfLL6EeZmNckOPzWc21QexNzM6OcqiGopscSFnmIqBc/pZf5G404AQBm/lFq+Gwu60pUD7qi79HfePrbb2

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: shutdown
